[pytest]
testpaths = SwagLabsUIAutomation/tests
addopts = --html=reports/report.html --self-contained-html --alluredir=reports/allure-results
markers =
    unit_test: marks tests as unit-tests
    integration: marks tests as integration tests
    e2e: marks tests as end-to-end tests
    no_dashboard_teardown: skips dashboard teardown after test
    no_reset: skips reset after login test