[pytest]
addopts = --html=reports/report.html --self-contained-html
markers =
    integration: marks tests as integration tests
    e2e: marks tests as end-to-end tests
    no_dashboard_teardown: skips dashboard teardown after test
    no_reset: skips reset after login test